### ISSUE TITLE
Networth not sending

### ISSUE THREAD

**Issue by JeffQT** [Altpapier/hypixel-discord-guild-bridge#11]
In some cases, when running the !nw command the bot will not send the message, Hypixel blocks it. In that chat log it shows "Advertising is against the rules. You will receive a punishment on the server if you attempt to advertise." when attempting to run it. I'm assuming it only occurs on networth over 1 billion because of the 4 commas, hypixel thinks it is a ip address. Maybe it is possible to abbreviate it to like 1.5B instead of something like 1,526,120,834
![image](https://user-images.githubusercontent.com/77899232/208267901-a6f0a391-d541-417b-8e13-ecb9d712f0e7.png)

**Comment by Altpapier** [comment]
https://github.com/Altpapier/hypixel-discord-guild-bridge/commit/48c6ce69d72c353328f03cdc50b5d5cfe9443a24
