### ISSUE TITLE
[Suggestion]

### ISSUE THREAD

**Issue by JeffQT** [Altpapier/hypixel-discord-guild-bridge#12]
Add a feature to blacklist people from the auto accept feature. If someone is kicked from the guild, they can join right back.

**Comment by Altpapier** [comment]
> Add a feature to blacklist people from the auto accept feature. If someone is kicked from the guild, they can join right back.

I added it but cannot test if it works as my guild has invites off and can't turn them on right now, so it would be nice if someone could test it out. Explanation of how the blacklist works is in the README.md file.
