### ISSUE TITLE
[Suggestion] Skyblock Level Guild Requirement

### ISSUE THREAD

**Issue by MattTheCuber** [Altpapier/hypixel-discord-guild-bridge#13]
As title says, can you add the ability to use Skyblock level as a guild requirement?

**Comment by Altpapier** [comment]
already exists

**Comment by MattTheCuber** [comment]
@Altpapier 
![image](https://user-images.githubusercontent.com/32849887/216766649-76fc3d52-388f-4fa4-8418-e44e86009859.png)
So Hypixel Level actually means SkyBlock level or?

**Comment by Altpapier** [comment]
> @Altpapier 
> ![image](https://user-images.githubusercontent.com/32849887/216766649-76fc3d52-388f-4fa4-8418-e44e86009859.png)
> So Hypixel Level actually means SkyBlock level or?

Seems like I forgot the example_config.json have a look into the readme its updated there
