### ISSUE TITLE
Error: Failed to obtain profile data for <email>, does this account own minecraft?

### ISSUE THREAD

**Issue by CraftedFury** [Altpapier/hypixel-discord-guild-bridge#14]
Started experiencing this error today when launching my docker container. The account does indeed has minecraft.

```
at Object.authenticate (/usr/src/app/node_modules/minecraft-protocol/src/client/microsoftAuth.js:31:40)
at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by Altpapier** [comment]
no idea what can cause that seems like this error comes from the mineflayer package that is used for the minecraft bot

**Comment by CraftedFury** [comment]
Just to answer this issue, this error happens when you get a suspension on your gmail account and try to login. Just incase you'd like to catch the error and give a more detailed explanation.
