### ISSUE TITLE
I recommend using /link for verification in a guild

### ISSUE THREAD

**Issue by Accardi22** [Altpapier/hypixel-discord-guild-bridge#3]
that the bot can give it a guild member rank in the discord by /link I don't see any use for it

**Comment by Altpapier** [comment]
> that the bot can give it a guild member rank in the discord by /link I don't see any use for it

I also added it using the username of your minecraft account when linked that might be more useful also for people that have a different username on discord than on minecraft

**Comment by Accardi22** [comment]
I like that but I said a verification system
