### ISSUE TITLE
requirement suggestion and more

### ISSUE THREAD

**Issue by Accardi22** [Altpapier/hypixel-discord-guild-bridge#4]
it would be nice if the bot had a way to calculate [.](the netword and if they could put the gun comados inside the game like other bot can e.g. https://github.com/DuckySoLucky/hypixel-discord-chat-bridge/tree/main/src/minecraft/commands) but I use your bot and I like it a lot and I have it in my guild.

**Comment by Altpapier** [comment]
the bot does have some ingame commands just not a lot https://github.com/Altpapier/hypixel-discord-guild-bridge#ingame-commands
I may add networth to it in the future idk yet
