### ISSUE TITLE
Crash when doing /g list

### ISSUE THREAD

**Issue by nickisnoobatcode** [Altpapier/hypixel-discord-guild-bridge#6]
The bridge bot crashes when typing /g list in the console channel. Presumably because the message is larger than the 2k character maximum but more importantly, pm2 doesn't auto restart the process when it crashes. I'm assuming it's because you catch uncaught exceptions (which is also bad practice), but I may be wrong.

**Comment by Altpapier** [comment]
pretty sure its a mineflayer issue have that with every minecraft bot

**Comment by Kathund** [comment]
can confirm its a problem with mineflayer. in my own bot i made using some info from this it will crash when getting the bot to run /g list
