### ISSUE TITLE
bug where the bot cant reconnect on it's own

### ISSUE THREAD

**Issue by Ozymandog** [Altpapier/hypixel-discord-guild-bridge#8]
Occasionally the bot disconnect but it doesn't reconnect to Hypixel on its own and the bridge doesn't work until I restart the code. Just thought I'd let you know so you could maybe write in the code for the bot to restart on it's own or something.

**Comment by Altpapier** [comment]
@Ozymandog make sure `unknownDisconnectRelog` is set to `true` in `config.json` in `options`
