### ISSUE TITLE
➜ and some other symbols show up as a error symbol in discord

### ISSUE THREAD

**Issue by thejacedev** [Altpapier/hypixel-discord-guild-bridge#9]
![sweatycuddles](https://user-images.githubusercontent.com/46321222/193943847-c53a416f-bae0-4e98-8545-34c514e6491e.png)

**Comment by Altpapier** [comment]
https://github.com/Altpapier/hypixel-discord-guild-bridge/commit/81d22c2b844ec7feb6f4d5e3787f429b3c7059ad
